---
title: ""
output: html_document
runtime: shiny
---
### It’s all about timing: Exploring the consequences of choosing different temporal resolutions for analyzing digital phenotyping data - Supplementary Material
```{r setup, include=FALSE}
library('dplyr')
library('ggplot2')
library('plotly')
library("runner")
library("hrbrthemes")
library("viridis")
library("ggpubr")
library("tidyr")
library("knitr")
library("dotwhisker")
library("stargazer")
library("lme4")


###### Scripts used ###########
# 0. Python script
# (1. data_matching.R)
# 2. Calculation Correlation.R
# 3. ParallelComputingML.R

###### Load dataframes #########
################################

####### Affect data #######
#24h missing
Affect_Passive <- read.csv("/Users/annalangener/Nextcloud/BEHAPP data/FullDataset_2709_24missing.csv")
Affect_Passive <- Affect_Passive[Affect_Passive$questionListName != "Morning assessment 1" & Affect_Passive$questionListName != "Morning Assessment",]

#12h
Affect_Passive_12m <- read.csv("/Users/annalangener/Nextcloud/BEHAPP data/FullDataset_2709_12missing.csv")
Affect_Passive_12m <- Affect_Passive_12m[Affect_Passive_12m$questionListName != "Morning assessment 1" & Affect_Passive_12m$questionListName != "Morning Assessment",]

#18h
Affect_Passive_18m <- read.csv("/Users/annalangener/Nextcloud/BEHAPP data/FullDataset_2709_18missing.csv")
Affect_Passive_18m <- Affect_Passive_18m[Affect_Passive_18m$questionListName != "Morning assessment 1" & Affect_Passive_18m$questionListName != "Morning Assessment",]

### Labeled following sensors as missing:
# Apps (whole day without app usage)
# Location (whole day without GPS coordinates, based on raw GPS)
# Wifi (whole day without wifi data)
# Bluetooth (whole day without Bluetooth data)

Affect_Passive_allsensor_NA <- Affect_Passive
Affect_Passive_allsensor_NA_12m <- Affect_Passive_12m
Affect_Passive_allsensor_NA_18m <- Affect_Passive_18m

Affect_Passive_allsensor_NA[is.na(Affect_Passive$APP_USAGE_min) | is.na(Affect_Passive$TIME_STATIONARY_min) | is.na(Affect_Passive$TOTAL_MACHASHES_number) | is.na(Affect_Passive$BLUETOOTH_TOTAL_MACHASHES_number),!colnames(Affect_Passive_allsensor_NA) %in% c("ParticipantNumber","Date", "pa_mean", "na_mean", "timescale_beforeESM")] <- NA

Affect_Passive_allsensor_NA_12m[is.na(Affect_Passive_12m$APP_USAGE_min) | is.na(Affect_Passive_12m$TIME_STATIONARY_min) | is.na(Affect_Passive_12m$TOTAL_MACHASHES_number) | is.na(Affect_Passive_12m$BLUETOOTH_TOTAL_MACHASHES_number),!colnames(Affect_Passive_allsensor_NA_12m) %in% c("ParticipantNumber","Date", "pa_mean", "na_mean", "timescale_beforeESM")] <- NA

Affect_Passive_allsensor_NA_18m[is.na(Affect_Passive_18m$APP_USAGE_min) | is.na(Affect_Passive_18m$TIME_STATIONARY_min) | is.na(Affect_Passive_18m$TOTAL_MACHASHES_number) | is.na(Affect_Passive_18m$BLUETOOTH_TOTAL_MACHASHES_number),!colnames(Affect_Passive_allsensor_NA_18m) %in% c("ParticipantNumber","Date", "pa_mean", "na_mean", "timescale_beforeESM")] <- NA

Affect_Passive_no_NA <- Affect_Passive

Affect_Passive_no_NA[is.na(Affect_Passive_no_NA)] <- 0

```

#### Temporal resolution while aggregating the data
```{r echo=FALSE}
source("Calculation Correlation.R")

# Missing values labeled single sensor specific
CorrelationSampleTrue <- calculateCorr_pa(Affect_Passive)

shinyApp(
  ui = fluidPage(
    selectInput(
      "Variable",
      label = "Variable: ",
      choices = unique(CorrelationSampleTrue$Feature),
      selected = CorrelationSampleTrue$Feature[1],
    ),
    plotOutput("Plot")
  ),
  
  server = function(input, output) {
    toListen <- reactive({
    list(input$Variable)
  })
    observeEvent(toListen(),{
      Variable = input$Variable
      
      cor1 =  ggplot(CorrelationSampleTrue[CorrelationSampleTrue$Feature == Variable, ],
                     aes(
                       y = as.factor(ParticipantNumber),
                       x = as.factor(timescale_beforeESM),
                       fill = Correlation
                     )) +
        geom_tile() +
        scale_fill_gradient2(low = "#D7191C", mid = "white", high = "#2C7BB6", limits =  c(-0.5,0.5)) +
        geom_text(aes(label = star), color = "black", size = 4) +
        ylab("") +
        xlab("") +
        ggtitle(paste("Correlation")) +
        theme_minimal()
    
 
      output$Plot = renderPlot({cor1},  height = 400, width = 400)
      
    })
  },
  options = list(height = 500, width = 500)
)
```


```{r echo=FALSE}
shinyApp(
  ui = fluidPage(
    selectInput(
      "Participant",
      label = "Participant: ",
      choices = c(117113,117114,117119,117121,117130,117129,117131,117134,117135,117137),
      selected = 117119
    ),
       selectInput(
      "PassiveMeasure",
      label = "Passive Measure: ",
       choices = c(
          'SOCIAL_min',
           'COMMUNICATION_min',
           'APP_USAGE_min',
           'APPS_OPENED_number',
           'Cluster_HOME_min',
           "Cluster_1_min",
           "Cluster_2_min",
           "Cluster_3_min",
           "Cluster_4_min",
           "Cluster_5_min" ,
           'UNIQUE_STAYPOINTS_number',
           'TIME_STATIONARY_min',
           'TOTAL_MACHASHES_number',
           'UNIQUE_MACHASHES_number',
           "BLUETOOTH_TOTAL_MACHASHES_number",
           "BLUETOOTH_UNIQUE_MACHASHES_number",
           'CALL_TOTAL_min',
           "CALL_incoming_min",
           "CALL_outgoing_min",
           "CALL_TOTAL_number",                                                   
           "CALL_incoming_number",                                                
           "CALL_outgoing_number",                                               
           "CALL_UNIQUE_CONTACTS_number",                                         
           "LIGHT_LUX_mean",                                                      
           "LIGHT_LUX_std",                                                       
           "SCREEN_onLocked_number" ,                                             
           "SCREEN_onUnlocked_number", 
           "SMS_received_number" ,                                                
           "SMS_sent_number" ,                                                    
           "SMS_UNIQUE_CONTACTS_number" 
      ),
      selected = "Cluster_HOME_min"
    ),
    plotOutput("Plot")
  ),
  
  server = function(input, output) {
    toListen <- reactive({
    list(input$Participant,input$PassiveMeasure)
  })
    observeEvent(toListen(),{
      Pnumber = input$Participant
      Feature <- input$PassiveMeasure
  
      source("https://raw.githubusercontent.com/datavizpyr/data/master/half_flat_violinplot.R")
            
      Affect_Passive$timescale_beforeESM <- ordered(Affect_Passive$timescale_beforeESM,levels = c("1h","3h","6h","9h","12h","24h"))
      
      Affect_Passive$timescale_beforeESM_num <- recode(Affect_Passive$timescale_beforeESM, "1h" = 1, "3h" = 3,"6h" = 6,"9h" = 9,"12h" = 12, "24h" = 24 )
      
      Affect_Passive[,"Passivecopy"] <- Affect_Passive[,colnames(Affect_Passive) == Feature]
      
 plot2 <- ggplot(Affect_Passive[Affect_Passive$ParticipantNumber == Pnumber,], aes(x=timescale_beforeESM, y=Passivecopy/timescale_beforeESM_num/60, fill = timescale_beforeESM, color = timescale_beforeESM)) + 
  geom_flat_violin(alpha = 0.5, position = position_nudge(x = 1.2, y = 0), width = 12) +
  geom_point(position = position_jitter(seed = 1, width = 1)) +
  theme_minimal() +
  xlab("") + 
  ylab("") +
  labs(fill='', color = '') +
  theme(legend.position = "none", axis.text.x=element_blank(),
        axis.ticks.x=element_blank(), text = element_text(size= 14), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  facet_grid(cols = vars(timescale_beforeESM)) +
  scale_color_manual(breaks = c("1h","3h","6h","9h","12h", "24h"),
                        values=c("#440154", "#443983", "#31688e","#21918c","#35b779","#90d743")) +
  scale_fill_manual(breaks = c("1h","3h","6h","9h","12h", "24h"),
                        values=c("#440154", "#443983", "#31688e","#21918c","#35b779","#90d743"))
 
 Home_scatter <- ggplot(Affect_Passive[Affect_Passive$ParticipantNumber == Pnumber,], aes(x = Passivecopy, y = pa_mean )) +
  geom_point(colour = "#440154FF" ) +
  geom_smooth(method="lm", se=TRUE, fullrange=FALSE, level=0.95, colour ="#21908CFF", fill ="#21908CFF") +
  stat_cor(method = "pearson",p.accuracy = 0.01, r.accuracy = 0.01, label.y = 0.3, label.sep = ",", label.x = 0, na.rm = TRUE, cor.coef.name = c("r")) +
  theme_minimal() +
  facet_grid(cols = vars(timescale_beforeESM), scales="free_x") +
  ylim(c(0,10)) +
  ylab("Positive Affect") +
  xlab("Passivecopy")  +
theme(text = element_text(size= 16), axis.text.x=element_text(hjust = 0.8))
    
 plot <- ggarrange(plot2, Home_scatter, ncol = 1, common.legend = FALSE, legend = "none") 
       
      output$Plot = renderPlot({plot})
      
    })
  },options = list(height = 600, width = 820)
)
```

#### Handling Missing Values
