---
title: "Time Scale Analysis"
author: "Anna Langener"
date: "3/1/2022"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("CorrelationPlot.R")
library(sjPlot)
library(jtools)
library(nlme)
library(dplyr)
library(ggplot2)
library(lme4)
library(dotwhisker)
library(ggpubr)
library(stargazer)
library(tidyr)
library(plotly)


PerStudy <- read.csv("/Users/annalangener/Nextcloud/BEHAPP data/PerStudy.csv")
PerWeek <- read.csv("/Users/annalangener/Nextcloud/BEHAPP data/PerWeek.csv")
PerDay <- read.csv("/Users/annalangener/Nextcloud/BEHAPP data/PerDay.csv")
PerHour <- read.csv("/Users/annalangener/Nextcloud/BEHAPP data/PerHour.csv")

to_analyze <- read.csv("/Users/annalangener/Google Drive/PhD Wellbeing/to_analyse.csv")
to_analyze <- to_analyze[,colnames(to_analyze) %in% c("BEHAPP_ID","SFS","LONELINESS")]

PerStudy <- left_join(PerStudy, to_analyze, by = c("ParticipantNumber" = "BEHAPP_ID"),suffix = c("",""))
PerWeek <- left_join(PerWeek, to_analyze, by = c("ParticipantNumber" = "BEHAPP_ID"),suffix = c("",""))
PerDay <- left_join(PerDay, to_analyze, by = c("ParticipantNumber" = "BEHAPP_ID"),suffix = c("",""))
PerHour <- left_join(PerHour, to_analyze, by = c("ParticipantNumber" = "BEHAPP_ID"),suffix = c("",""))

set.seed(12361488)
train_ind <- sample(PerStudy$ParticipantNumber, size = 0.7*nrow(PerStudy))

PerHourtrain <- PerHour[PerHour$ParticipantNumber %in% train_ind, ]
PerHourtest <- PerHour[!PerHour$ParticipantNumber %in% train_ind, ]

PerDaytrain <- PerDay[PerDay$ParticipantNumber %in% train_ind, ]
PerDaytest <- PerDay[!PerDay$ParticipantNumber %in% train_ind, ]

PerWeektrain <- PerWeek[PerWeek$ParticipantNumber %in% train_ind, ]
PerWeektest <- PerWeek[!PerWeek$ParticipantNumber %in% train_ind, ]

PerStudytrain <- PerStudy[PerStudy$ParticipantNumber %in% train_ind, ]
PerStudytest <- PerStudy[!PerStudy$ParticipantNumber %in% train_ind, ]


# NA not replaced
PerHourNA <- PerHour
PerHourNA[is.na(PerHourNA)] <- 0
PerDayNA <- PerDay
PerDayNA[is.na(PerDayNA)] <- 0
PerWeekNA <- PerWeek
PerWeekNA[is.na(PerWeekNA)] <- 0
PerStudyNA <- PerStudy
PerStudyNA[is.na(PerStudyNA)] <- 0


# library(mice)
# 
# col = c("COMMUNICATION_APPS_pct","SOCIAL_APPS_pct","APP_USAGE_pct","SOCIAL_APPS_min","COMMUNICATION_APPS_min","APP_USAGE_min","APPS_OPENED_number","CLUSTER_HOME_pct"," TIME_STATIONARY_pct","CLUSTER_HOME_min","NUMBER_STAYPOINTS_number","UNIQUE_STAYPOINTS_number","TIME_STATIONARY_min","TOTAL_MACHASHES_norm","UNIQUE_MACHASHES_norm","CALL_incoming_pct","CALL_outgoing_pct","CALL_TOTAL_pct","MISSED_CALLS_norm", "ParticipantNumber", "Date")
# 
# 
# 
# PerDayC <- mice(PerDay[,colnames(PerDay) %in% col])
# PerDayC <- complete(PerDayC)
# data.all.mt = model.matrix(~ COMMUNICATION_APPS_pct+SOCIAL_APPS_pct+APP_USAGE_pct+COMMUNICATION_APPS_min+APP_USAGE_min+APPS_OPENED_number+CLUSTER_HOME_pct+CLUSTER_HOME_min+NUMBER_STAYPOINTS_number+UNIQUE_STAYPOINTS_number+TIME_STATIONARY_min+TOTAL_MACHASHES_norm+UNIQUE_MACHASHES_norm+CALL_incoming_pct+CALL_outgoing_pct+CALL_TOTAL_pct+MISSED_CALLS_norm, PerDayC)[,-1]
# data.pca = princomp(data.all.mt)
# 
# n.pcs = 5
# X.data.pca = data.pca$scores[,1:n.pcs]
# df.tmp = data.frame(X.data.pca, ID = PerDayC$ParticipantNumber, day = PerDayC$Date)
# colnames(df.tmp)[ncol(df.tmp)] = outcome
# return( split(df.tmp, df.tmp$ID) )

```


## Correlation Passive Measures and Social Functioning/ Loneliness
0.1 Small
0.3 Moderate
0.5 Large

Cohen's (1988)

```{r echo=FALSE}
shinyApp(

  ui = fluidPage(
    selectInput("CorrelationPair", label = "Correlation with: ",
              choices = c("LONELINESS","SFS"), selected = "SFS"),
    plotlyOutput("Plot")
  ),

server = function(input, output) {
  
  Features <- c('SOCIAL_APPS_pct','APP_USAGE_pct','APPS_OPENED_norm', 'SOCIAL_APPS_min','COMMUNICATION_APPS_pct','COMMUNICATION_APPS_min', 'APP_USAGE_min', 'APPS_OPENED_number','CLUSTER_HOME_pct','NUMBER_STAYPOINTS_norm', 'UNIQUE_STAYPOINTS_norm', 'TIME_STATIONARY_pct','CLUSTER_HOME_min', 'NUMBER_STAYPOINTS_number', 'UNIQUE_STAYPOINTS_number', 'TIME_STATIONARY_min', 'TOTAL_MACHASHES_norm', 'UNIQUE_MACHASHES_norm', 'CALL_incoming_pct', 'CALL_outgoing_pct', 'CALL_TOTAL_pct', 'MISSED_CALLS_norm')

  observeEvent(input$CorrelationPair,{
CorrelationPair = input$CorrelationPair

Correlation <- data.frame(Correlation = cor.test(PerHour[,Features[1]],PerHour[,CorrelationPair])$estimate, p.value = round(cor.test(PerHour[,Features[1]],PerHour[,CorrelationPair])$p.value,2), Feature = Features[1], Time = "Per Hour")

Correlation <- rbind(Correlation, data.frame(Correlation = cor.test(PerDay[,Features[1]],PerDay[,CorrelationPair])$estimate, p.value = round(cor.test(PerDay[,Features[1]],PerDay[,CorrelationPair])$p.value,2), Feature = Features[1], Time = "Per Day"))

Correlation <-  rbind(Correlation, data.frame(Correlation = cor.test(PerWeek[,Features[1]],PerWeek[,CorrelationPair])$estimate, p.value = round(cor.test(PerWeek[,Features[1]],PerWeek[,CorrelationPair])$p.value,2), Feature = Features[1], Time = "Per Week"))

Correlation <-  rbind(Correlation, data.frame(Correlation = cor.test(PerStudy[,Features[1]],PerStudy[,CorrelationPair])$estimate, p.value = round(cor.test(PerStudy[,Features[1]],PerStudy[,CorrelationPair])$p.value,2), Feature = Features[1], Time = "Per Study"))


for(i in 2:length(Features)){
  Correlation <- rbind(Correlation,data.frame(Correlation = cor.test(PerHour[,Features[i]],PerHour[,CorrelationPair])$estimate, p.value = round(cor.test(PerHour[,Features[i]],PerHour[,CorrelationPair])$p.value,2), Feature = Features[i], Time = "Per Hour"))
  
  Correlation <-  rbind(Correlation, data.frame(Correlation = cor.test(PerDay[,Features[i]],PerDay[,CorrelationPair])$estimate, p.value = round(cor.test(PerDay[,Features[i]],PerDay[,CorrelationPair])$p.value,2), Feature = Features[i], Time = "Per Day"))

Correlation <-  rbind(Correlation, data.frame(Correlation = cor.test(PerWeek[,Features[i]],PerWeek[,CorrelationPair])$estimate, p.value = round(cor.test(PerWeek[,Features[i]],PerWeek[,CorrelationPair])$p.value,2), Feature = Features[i], Time = "Per Week"))

Correlation <-  rbind(Correlation, data.frame(Correlation = cor.test(PerStudy[,Features[i]],PerStudy[,CorrelationPair])$estimate, p.value = round(cor.test(PerStudy[,Features[i]],PerStudy[,CorrelationPair])$p.value,2), Feature = Features[i], Time = "Per Study"))

}

Correlation$Star <- ""
Correlation$stars <- cut(Correlation$p.value, breaks=c(-Inf, 0.001, 0.01, 0.05, Inf), label=c("***", "**", "*", ""))
Correlation$Time <- factor(Correlation$Time, levels = c("Per Hour", "Per Day", "Per Week", "Per Study"))


output$Plot = renderPlotly({
ggplotly(
  ggplot(Correlation, aes(y= Feature,x = Time, fill= Correlation)) + 
  geom_tile() +
  scale_fill_gradient2(low="#D7191C", mid="white", high="#2C7BB6") + 
  geom_text(aes(label=stars), color="black", size=4) +
  ylab("") +
  xlab("") +
  ggtitle((paste("Correlation Passive Measures and",CorrelationPair))) +
  theme_minimal())

})
})
})
```


### Association Between Features
```{r echo=FALSE}
inputPanel(
    selectInput("Variable1", label = "Variable 1: ",
              choices = c('COMMUNICATION_APPS_pct','SOCIAL_APPS_pct','APP_USAGE_pct', 'SOCIAL_APPS_min','COMMUNICATION_APPS_min', 'APP_USAGE_min', 'APPS_OPENED_number','CLUSTER_HOME_pct', 'TIME_STATIONARY_pct','CLUSTER_HOME_min', 'NUMBER_STAYPOINTS_number', 'UNIQUE_STAYPOINTS_number', 'TIME_STATIONARY_min', 'TOTAL_MACHASHES_norm', 'UNIQUE_MACHASHES_norm', 'CALL_incoming_pct', 'CALL_outgoing_pct', 'CALL_TOTAL_pct', 'MISSED_CALLS_norm'), selected = "CLUSTER_HOME_pct"),
        selectInput("Variable2", label = "Variable 2: ",
              choices = c('COMMUNICATION_APPS_pct','SOCIAL_APPS_pct','APP_USAGE_pct', 'SOCIAL_APPS_min','COMMUNICATION_APPS_min', 'APP_USAGE_min', 'APPS_OPENED_number','CLUSTER_HOME_pct', 'TIME_STATIONARY_pct','CLUSTER_HOME_min', 'NUMBER_STAYPOINTS_number', 'UNIQUE_STAYPOINTS_number', 'TIME_STATIONARY_min', 'TOTAL_MACHASHES_norm', 'UNIQUE_MACHASHES_norm', 'CALL_incoming_pct', 'CALL_outgoing_pct', 'CALL_TOTAL_pct', 'MISSED_CALLS_norm'), selected = "COMMUNICATION_APPS_pct"))

renderPlot({CorrelationPlot(Feature = c(input$Variable1,input$Variable2),PerHour,PerDay,PerWeek,PerStudy,PerHourNA,PerDayNA,PerWeekNA,PerStudyNA)
})

```



